name: "PHP Web Server"
version: "1.0.1"
slug: "php_webserver"
description: "PHP web server with access to Home Assistant configuration directory"
url: "https://github.com/TillitschScHocK/PHP4HA"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
webui: "http://[HOST]:[PORT:8099]"
ingress: false
panel_icon: mdi:language-php
options:
  port: 8099
  subdirectory: "php"
  php_display_errors: "Off"
  php_memory_limit: "128M"
schema:
  port: port
  subdirectory: str
  php_display_errors: list(On|Off)
  php_memory_limit: str
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: PHP Web Server
map:
  - config:rw
