name: "PHP Web Server"
version: "1.0.0"
slug: "php_webserver"
description: "PHP web server with access to Home Assistant configuration directory"
url: "https://github.com/TillitschScHocK/PHP4HA"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
options:
  port: 8099
  document_root: "/config/www"
  php_display_errors: "Off"
  php_memory_limit: "128M"
schema:
  port: port
  document_root: str
  php_display_errors: list(On|Off)
  php_memory_limit: str
ports:
  8099/tcp: 8099
map:
  - config:rw
image: "ghcr.io/tillitschschock/php4ha-{arch}"
